name: Compiler checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        check-command: ["pytest", "mypy -m compiler"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: compiler
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest mypy
          pip install -r requirements.txt
      - name: Check with ${{ matrix.check-command }}
        working-directory: compiler
        run: ${{ matrix.check-command }}
