name: Deploy pages

on:
  push:
    branches: master

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        working-directory: compiler
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            graphviz \
            texlive-base \
            texlive-binaries \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build results markdown
        run: ./compiler/make_results_markdown.py static
      - name: Build paper
        run: |
          yes '' | pdflatex paper_SIMD.tex || true
          mv paper_SIMD.pdf static
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: static
